preset: laravel
enabled:
  - concat_with_spaces
disabled:
  - no_unused_imports
  - concat_without_spaces
finder:
  exclude:
    - "legacy"
    - "modules"
    - "node_modules"
    - "nova"
    - "nova-components"
    - "storage"
    - "spark"
    - "vendor"
  not-name:
    - "index.php"
    - "server.php"
    - "*.blade.php"
    - "_ide_helper.php"
