# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.4.16

definitions:
  steps:
    - step: &gitdiffdeploy
        name: Git Diff & Deploy
        deployment: production
        script:
          - apt-get update && apt-get install -y unzip git git-core
          - LASTCOMMITHASH=`git rev-parse @`
          - PREVIOUSCOMMITHASH=`git rev-parse @~`
          - echo "Last commit is $LASTCOMMITHASH"
          - echo "Previous commit is $PREVIOUSCOMMITHASH"
          - git archive -o output.zip $LASTCOMMITHASH $(git diff --diff-filter=ACMRTUXB --name-only $PREVIOUSCOMMITHASH $LASTCOMMITHASH)
          - find . -type f ! -iname "output.zip" -delete
          - mkdir deploy && ls
          - unzip output.zip -d deploy
          - cd deploy && ls -R
          - cd ..
          - pipe: atlassian/ftp-deploy:0.3.5
            variables:
              USER: $FTP_MONDEGC_USERNAME
              PASSWORD: $FTP_MONDEGC_PASSWORD
              SERVER: $FTP_MONDEGC_HOST
              REMOTE_PATH: '/'
              LOCAL_PATH: "deploy"
              DELETE_FLAG: 'false' # Don't delete existing files
              DEBUG: 'true'
    - step: &buildtest
        name: Build/Test
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install --ignore-platform-reqs
          - php artisan monde:init
        artifacts:
          - vendor/**
    - step: &pushgithubmaster
        name: Push To GitHub (master)
        clone:
          depth: full
        script:
          - apt-get update && apt-get install -y unzip git git-core
          - git remote add sync git@github.com:Roxayl/mondegc.git
          - git checkout master
          - git pull
          - git push sync master
    - step: &pushgithubdevelop
        name: Push To GitHub (develop)
        clone:
          depth: full
        script:
          - apt-get update && apt-get install -y unzip git git-core
          - git remote add sync git@github.com:Roxayl/mondegc.git
          - git checkout develop
          - git pull
          - git push sync develop

pipelines:
  branches:
    develop:
      - step: *buildtest
      - parallel:
        - step: *pushgithubdevelop
        - step: *gitdiffdeploy
    master:
      - step: *buildtest
      - parallel:
        - step: *pushgithubmaster
        - step: *gitdiffdeploy