# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:8.0

definitions:
  steps:

    - step: &pushLaravelCodeToGitHub
        name: Push Laravel Code to GitHub
        clone:
          depth: full
        script:
          - apt-get update && apt-get install -y unzip git git-core
          - COMMIT_MESSAGE=`git log --format=%B -n 1 $BITBUCKET_COMMIT`
          - COMMITTER_NAME=`git log --format=%an -n 1 $BITBUCKET_COMMIT`
          - COMMITTER_MAIL=`git log --format=%ae -n 1 $BITBUCKET_COMMIT`
          - rm -rf .git
          - git init
          - git remote add sync git@github.com:Roxayl/mondegc-laravel.git
          - set +e
          - git fetch && git pull --rebase
          - set -e
          - ls
          - rm -f -r legacy
          - rm -f -r .github
          - git add .
          - git config user.email "$COMMITTER_MAIL"
          - git config user.name "$COMMITTER_NAME"
          - git commit -m "$COMMIT_MESSAGE"
          - git push sync --mirror

pipelines:
  branches:

    "{master,develop}":
      - step: *pushLaravelCodeToGitHub
