version: "3"

services:

  app:
    build: .
    container_name: mondegc_app
    ports:
      - "80:80"
    tty: true
    volumes:
      - ../:/var/www/html:cached
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_UPLOAD_MAX_FILESIZE: 64M
      PHP_INI_POST_MAX_SIZE: 64M
      PHP_INI_DISPLAY_ERRORS: 1
      PHP_INI_STARTUP_ERRORS: 1
      PHP_INI_DATE__TIMEZONE: Europe/Paris
      APACHE_DOCUMENT_ROOT: /var/www/html

  mysql:
    image: mysql:5.7
    container_name: mondegc_mysql
    ports:
      - "3306:3306"
    volumes:
      - ../docker/mysql/data:/var/lib/mysql
      - ../docker/mysql/entrypoint:/docker-entrypoint-initdb.d
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=IGNORE_SPACE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mondegc_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    links:
      - mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mondegc_mailhog
    logging:
      driver: "none"  # disable saving logs
    ports:
      - "1025:1025"  # smtp server
      - "8025:8025"  # web ui
