version: "3"

services:

  app:
    build: .
    container_name: mondegc_app
    ports:
      - "80:80"
    tty: true
    volumes:
      - ../:/workspace:cached
    environment:
      APP_ENV: local
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_MYSQL: 1
      PHP_EXTENSION_PDO_MYSQL: 1
      APACHE_DOCUMENT_ROOT: /workspace/public

  mysql:
    image: mysql:8.0
    container_name: mondegc_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/entrypoint:/docker-entrypoint-initdb.d
    command: [mysqld,
        --default-authentication-plugin=mysql_native_password,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci]
    environment:
      MYSQL_ROOT_PASSWORD: root

  mailhog:
    image: mailhog/mailhog
    container_name: mondegc_mailhog
    logging:
      driver: "none"
    ports:
      - "8025:8025"
