name: "🔄 Sync with external repository"

on: push

jobs:

  sync-to-bitbucket:
    name: "🔄 Sync with Bitbucket"
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout full repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Mirror repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@bitbucket.org:Roxayl/mondegc.git
          ssh_private_key:
            ${{ secrets.BITBUCKET_SSH_PRIVATE_KEY }}
