name: "⬆️ Update release"

on:
  release:
    types: [published]

jobs:
  update-release:
    name: "⬆️ Bump production release"
    runs-on: ubuntu-20.04

    steps:

      - name: Run SSH commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          script: |
            cd "${{ vars.PROD_FULL_DIR }}"
            VERSION_NUMBER="${{ github.event.release.name }}"
            find ./.env -type f -exec sed -i '' -e "/^APP_VERSION=/s/=.*/=\'$VERSION_NUMBER\'/" {} \;
